### ISSUE TITLE
Don't seperate the 68k code

### ISSUE THREAD

**Issue by radioshadow** [Nasina7/puyodisasm#2]
I made the same mistake when updating Dr. Robotnik's Mean Bean disassembly (and I want to get that fixed). I wanted to split the code into sections, thinking it would make it easier to find the required code, but it makes it very tricking when jumping to subroutines when the code is divided into other files.

If you look at the Sonic 1 / 2 disassembly, they don't split the code, to prevent the above issues from happening.

My advice would be to put the code in the "game" folder back into the "puyo.asm".

Otherwise, what you have put together is good so far.

**Comment by Nasina7** [comment]
I've been uncertain about having it separated lately as well.  It shouldn't be too difficult to move it back into puyo.asm (Unless I'm forgetting something).  I'll probably keep the cutscene folder separate and just move it to the root of the disassembly since all it contains is cutscene data and not actual code.  I'll probably do the same with the bytecode folder as well (move the code back to puyo.asm, and keep the table / macros separate).

I'll do this in the next commit, which should be in a few days.  As a side note, if you know of any info from the Mean Bean disassembly that might be missing from this, let me know.  I have looked at your disassembly occasionally, but I haven't looked through it thoroughly for info yet.

**Comment by radioshadow** [comment]
I agree on keeping the cut-scenes, tables and macros separate, while the rest be moved back to the Puyo.asm. :)

I do have some other stuff I can contribute (I know where the mappings are for the crumbling tiles). I'll raise them as separate issues.

**Comment by Nasina7** [comment]
Fixed in commit 49ac01c.
